import fs from 'node:fs';
import assert from 'node:assert/strict';
const catalog = JSON.parse(fs.readFileSync('data/games.json','utf8'));
const esc = (value) => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const js = (value) => JSON.stringify(value).replaceAll('<','\\u003c');
const common = ['ko','en','de','fr','ja','es'];
const setup=JSON.parse(fs.readFileSync('data/setup.json','utf8'));
fs.writeFileSync('assets/setup-data.js','// Generated from data/setup.json.\nwindow.BGW_SETUP = '+js(setup)+';\n');
assert.equal(new Set(catalog.map(g=>g.id)).size,catalog.length,'Duplicate game ID');
fs.writeFileSync('assets/games.js', '// Generated from data/games.json; run node scripts/build-site.mjs.\nwindow.BGW_GAMES = '+js(catalog)+';\n');
for(const game of catalog.filter(g=>g.reference)) {
 const data=JSON.parse(fs.readFileSync(game.reference,'utf8'));
 data.titles = game.titles;
 assert.equal(data.schemaVersion,1);
 assert.equal(data.id,game.id);
 assert.deepEqual(data.languages,game.languages);
 const ids=new Set(), signatures=new Set();
 for(const item of data.items){
  assert.ok(!ids.has(item.id),'Duplicate item ID: '+item.id);ids.add(item.id);
  assert.ok(data.categories.some(c=>c.id===item.category),'Unknown category');
  const sig=JSON.stringify([item.category,item.number || '',item.name.en,item.text.en]);
  assert.ok(!signatures.has(sig),'Duplicate reference: '+item.id);signatures.add(sig);
  for(const lang of data.languages)assert.ok(item.name[lang]&&item.text[lang],'Missing translation');
  if(item.image)assert.ok(fs.existsSync(game.id+'/'+item.image),'Missing image '+item.image);
 }
 fs.writeFileSync(game.id+'/reference-data.js','// Generated from reference.json.\nwindow.BGW_REFERENCE = '+js(data)+';\n');
 const canonical='https://ossonida.github.io/'+game.id+'/';
 const alternates=data.languages.map(lang=>`  <link rel="alternate" hreflang="${lang}" href="${canonical}?lang=${lang}">`).join('\n');
 const fallback=data.categories.map(cat=>`<section><h2>${esc(cat.name.ko || cat.name.en)}</h2>${data.items.filter(i=>i.category===cat.id).map(i=>`<article><h3>${esc([i.number,i.name.ko || i.name.en].filter(Boolean).join(' · '))}</h3><p>${esc(i.text.ko || i.text.en)}</p></article>`).join('')}</section>`).join('\n');
 fs.writeFileSync(game.id+'/index.html',`<!doctype html>
<!-- Generated by scripts/build-site.mjs. Edit reference.json and shared assets. -->
<html lang="ko"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>BGW : ${esc(data.title)}</title>
  <meta name="description" content="${esc(data.description.ko || data.description.en)}">
  <link rel="canonical" href="${canonical}">
${alternates}
  <link rel="alternate" hreflang="x-default" href="${canonical}">
  <meta property="og:title" content="BGW : ${esc(data.title)}">
  <meta property="og:url" content="${canonical}">
  <link rel="stylesheet" href="../assets/reference-layout.css">
  <link rel="stylesheet" href="../assets/reference.css">
</head><body data-setup-game="${esc(data.id)}">
<a class="skip" id="skip" href="#results">레퍼런스로 이동</a>
<main class="layout">
<div class="page-top">

<div class="page-top-row game-header-row"><a class="home-link" aria-label="홈으로 이동" id="home" data-site-link href="../"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10.8 12 3l9 7.8v9.7H15v-6H9v6H3Z" fill="none" stroke="currentColor" stroke-width="2"/></svg></a><span class="header-separator" aria-hidden="true">·</span><h1 class="page-title" id="page-title">${esc(data.title)}</h1>
<div class="top-actions">${game.id==='clocktower'?'':"<a class=\"score-counter-link\" href=\"https://ossonida.github.io/score/\"><svg class=\"score-counter-icon\" viewBox=\"0 0 24 24\" aria-hidden=\"true\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"2\"/><path d=\"M7 8h3v4H7zM14 8h3v4h-3zM8.5 15v3M7 16.5h3M14 16.5h3\"/></svg><span>Score Counter</span></a>"}<a class="coffee-banner" href="https://github.com/sponsors/ossonida" target="_blank" rel="noopener noreferrer">☕ Coffee</a>
<div class="lang-switch" id="lang-switch"><button type="button" id="lang-button" aria-label="Language" aria-haspopup="listbox" aria-controls="lang-menu" aria-expanded="false"><span class="lang-label"><img class="lang-icon" id="lang-icon" src="../img/flag-kr.svg" alt=""><span id="lang-code">KR</span></span><span aria-hidden="true">▾</span></button><div class="lang-menu" id="lang-menu" role="listbox" aria-label="Language" hidden></div></div></div></div>
<div class="filter-tabs" id="filters" role="group" aria-label="Categories"></div>
<div class="search-bar"><input id="search" type="search" aria-label="검색" placeholder="검색" autocomplete="off"></div>
<p class="count" id="count" role="status" aria-live="polite"></p></div>
<div class="reference-results" id="results"></div><p class="empty" id="empty" hidden></p>
<noscript>${fallback}</noscript>
<footer>${data.communityBadge ? `<div class="community-badge"><img src="${esc(data.communityBadge)}" alt="Community Created Content" loading="lazy"></div>` : ""}<a href="mailto:bgame.wiki@gmail.com">Any Feedback</a></footer>
</main>
<dialog id="image-dialog" aria-labelledby="modal-title"><button type="button" id="modal-close">닫기</button><h2 id="modal-title"></h2><img id="modal-image" alt=""><p id="modal-text"></p></dialog>
<script src="../assets/site.js"></script><script src="reference-data.js"></script><script src="../assets/reference.js"></script>
<script src="../assets/setup-data.js"></script><script src="../assets/setup.js"></script>
</body></html>\n`);
}

 // Publish legacy game sources under routes owned by the unified site.
 for(const id of ['gah','marrakesh']){
  const target='games/'+id;
  fs.cpSync(id,target,{recursive:true});
  const page=fs.readFileSync(target+'/index.html','utf8')
   .replaceAll('https://ossonida.github.io/'+id+'/', 'https://ossonida.github.io/games/'+id+'/')
   .replaceAll('../assets/', '../../assets/')
   .replace('data-site-link href="../"', 'data-site-link href="../../"');
  fs.writeFileSync(target+'/index.html',page);
 }

let hub=fs.readFileSync('index.html','utf8');
const list=catalog.map(game=>`          <li>${game.href?`<a href="${esc(game.href)}">BGW : ${esc(game.title)}</a>`:`BGW : ${esc(game.title)} - 준비중`}</li>`).join('\n');
hub=hub.replace(/(<noscript>[\s\S]*?<ul>)[\s\S]*?(<\/ul>)/,`$1\n${list}\n        $2`);
fs.writeFileSync('index.html',hub);
const entries=[{href:'./',languages:common},...catalog.filter(g=>g.href)];
let sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n';
for(const game of entries){
 const base=new URL(game.href,'https://ossonida.github.io/').href;
 for(const url of [base,...game.languages.map(l=>base+'?lang='+l)]){
  sitemap+=`  <url><loc>${esc(url)}</loc>\n`;
  for(const lang of game.languages)sitemap+=`    <xhtml:link rel="alternate" hreflang="${lang==='zh'?'zh-CN':lang}" href="${esc(base+'?lang='+lang)}" />\n`;
  sitemap+=`    <xhtml:link rel="alternate" hreflang="x-default" href="${base}" />\n  </url>\n`;
 }
}
fs.writeFileSync('sitemap.xml',sitemap+'</urlset>\n');
console.log(`Built catalog, ${catalog.filter(g=>g.reference).length} shared reference page(s), hub fallback and sitemap.`);
