"""Import official BotC base editions from a downloaded translation snapshot.
Usage: python scripts/import-clocktower.py tmp/botc
Required: roles.json, nightsheet.json, {ko,en,de,fr,ja,es}.json, app-{lang}.json.
Data: https://release.botc.app/resources/ and
https://github.com/ThePandemoniumInstitute/botc-translations (game/ and app/).
Images are stored locally in clocktower/images; no network during site builds.
"""
import json,sys
from pathlib import Path
source=Path(sys.argv[1]); target=Path('clocktower');target.mkdir(exist_ok=True)
langs=['ko','en','de','fr','ja','es']
def read(name):return json.loads((source/(name+'.json')).read_text(encoding='utf-8'))
def tr(*values):assert len(values)==6;return dict(zip(langs,values))
translations={l:read(l) for l in langs}; apps={l:read('app-'+l) for l in langs}
roles=[r for r in read('roles') if r.get('edition') in ['tb','bmr','snv','carousel'] or r['id']=='stormcatcher']
carousel=tr('캐러셀','The Carousel','The Carousel','The Carousel','The Carousel','The Carousel')
night=read('nightsheet'); teams=['townsfolk','outsider','minion','demon','traveller','fabled','loric']
team=lambda t,l:apps[l]['grimoire'][t].split('|')[0]
edition=lambda e,l:carousel[l] if e=='carousel' else translations[l]['editions'][e]['name']
titles=tr('시계탑에 흐른 피','Blood on the Clocktower','Blood on the Clocktower','Blood on the Clocktower','ブラッド・オン・ザ・クロックタワー','Blood on the Clocktower')
description=tr('기본판 3개 시나리오 + 캐러셀 72종 · 역할·밤 순서·셋업','Three base scripts + The Carousel: 72 characters · roles, night order and setup','Drei Grundskripte + The Carousel: 72 Charaktere · Rollen, Nachtreihenfolge und Aufbau','Trois scénarios de base + The Carousel : 72 personnages · rôles, ordre nocturne et préparation','基本3台本 + The Carousel 72種 · 役職・夜の順番・セットアップ','Tres guiones básicos + The Carousel: 72 personajes · roles, orden nocturno y preparación')
data={'schemaVersion':1,'id':'clocktower','title':titles['en'],'titles':titles,'languages':langs,'description':description,'communityBadge':'images/community.png','categories':[],'items':[],'source':{'roles':'https://release.botc.app/resources/data/roles.json','translations':'https://github.com/ThePandemoniumInstitute/botc-translations','nightOrder':'https://release.botc.app/resources/data/nightsheet.json','rules':'https://wiki.bloodontheclocktower.com/Rules_Explanation','setup':'https://wiki.bloodontheclocktower.com/Setup','policy':'https://bloodontheclocktower.com/pages/community-created-content-policy'}}
for e in ['tb','bmr','snv','carousel']:data['categories'].append({'id':e,'name':{l:edition(e,l) for l in langs}})
custom_label=tr('커스텀 시트','Custom script','Benutzerdefiniertes Skript','Script personnalisé','カスタム台本','Guion personalizado')
custom_scripts=json.loads((target/'custom-scripts.json').read_text(encoding='utf-8'))
for script in custom_scripts:
 data['categories'].append({'id':script['id'],'name':{l:script['name'] for l in langs},'description':{l:f"{custom_label[l]} · {script['author']} · v{script['version']}" for l in langs},'items':script['roles']})
for key,name in [('traveller',{l:team('traveller',l) for l in langs}),('flow',tr('진행·핵심 규칙','Flow & rules','Ablauf & Regeln','Déroulement et règles','進行・基本ルール','Desarrollo y reglas')),('night',tr('밤 순서','Night order','Nachtreihenfolge','Ordre nocturne','夜の順番','Orden nocturno')),('setup',tr('셋업','Setup','Spielaufbau','Mise en place','セットアップ','Preparación'))]:data['categories'].append({'id':key,'name':name})
for e in ['tb','bmr','snv','carousel']:
 for r in sorted([r for r in roles if r['edition']==e or (e=='carousel' and r['id']=='stormcatcher')],key=lambda r:(teams.index(r['team']),r['name'])):
  role={l:translations[l]['roles'][r['id']] for l in langs}
  assert all(role[l].get('name') and role[l].get('ability') for l in langs),r['id']
  data['items'].append({'id':r['id'],'category':'carousel' if e=='carousel' else 'traveller' if r['team']=='traveller' else e,'edition':e,'team':r['team'],'image':'images/'+r['id']+'.webp','name':{l:role[l]['name'] for l in langs},'text':{l:team(r['team'],l)+' · '+(edition(e,l)+' · ' if r['team']=='traveller' else '')+role[l]['ability'] for l in langs}})
def add(id,cat,name,text):data['items'].append({'id':id,'category':cat,'name':name,'text':text})
add('flow-win','flow',tr('승리 조건','Victory','Sieg','Victoire','勝利条件','Victoria'),tr('선은 악마가 모두 사망하면, 악은 생존자가 2명만 남으면 승리합니다. 역할의 특별 승리 조건이 우선하며, 여행자는 이 생존자 수에서 제외합니다.','Good wins when all Demons are dead; evil wins with only 2 living players. Character exceptions override this. Travellers do not count toward this total.','Gut gewinnt, wenn alle Dämonen tot sind; Böse bei nur 2 Lebenden. Sonderregeln der Charaktere gehen vor. Reisende zählen dabei nicht mit.','Le Bien gagne quand tous les Démons sont morts ; le Mal lorsqu’il ne reste que 2 joueurs vivants. Les exceptions des personnages priment. Les Voyageurs sont exclus de ce total.','悪魔が全員死亡すると善が勝利、生存者が2人になると悪が勝利。キャラクターの例外が優先され、旅人はこの人数に数えません。','El bien gana cuando todos los Demonios mueren; el mal cuando solo quedan 2 vivos. Las excepciones de personajes prevalecen. Los Viajeros no cuentan para este total.'))
add('flow-vote','flow',tr('지명·투표','Nominations & votes','Nominieren & Abstimmen','Nominations et votes','指名・投票','Nominaciones y votos'),tr('매일 생존자는 1회 지명할 수 있고, 각 플레이어는 1회 지명될 수 있습니다. 생존자 수의 절반 이상(올림)의 표가 필요합니다. 최다 득표자 1명을 처형하며 최다 동률이면 처형하지 않습니다. 역할에 따른 예외가 있습니다.','Each living player may nominate once per day; each player may be nominated once. At least half the living players’ number of votes (rounded up) is needed. Execute the unique highest tally; a tie means no execution. Character exceptions apply.','Jeder Lebende darf täglich einmal nominieren; jeder Spieler darf einmal nominiert werden. Nötig sind Stimmen von mindestens der Hälfte der Lebenden (aufgerundet). Nur der eindeutige Höchstwert führt zur Hinrichtung; bei Gleichstand niemand. Charakterregeln können abweichen.','Chaque vivant peut nommer une fois par jour ; chaque joueur peut être nommé une fois. Il faut au moins la moitié du nombre de vivants, arrondie au supérieur, en voix. Seul le plus haut total unique mène à une exécution ; une égalité l’annule. Exceptions de personnages possibles.','生存者は1日に1回指名でき、各プレイヤーは1日に1回指名されます。必要票数は生存者数の半分（切り上げ）。単独最多票の人を処刑し、最多同数なら処刑なし。能力による例外があります。','Cada vivo puede nominar una vez al día; cada jugador puede ser nominado una vez. Se necesita al menos la mitad de los vivos en votos, redondeando hacia arriba. Se ejecuta al máximo único; un empate impide la ejecución. Hay excepciones por habilidades.'))
add('flow-dead','flow',tr('사망 후','After death','Nach dem Tod','Après la mort','死亡後','Tras morir'),tr('사망해도 토론과 팀 승패에 참여합니다. 일반적으로 능력과 지명권을 잃고, 남은 게임 동안 투표는 1회만 할 수 있습니다. 죽어서도 작동하는 능력은 예외입니다.','Dead players still talk and share their team’s result. Normally they lose their ability and cannot nominate, with only one vote for the rest of the game. Abilities that work while dead are exceptions.','Tote reden weiter und gewinnen oder verlieren mit ihrem Team. Normalerweise verlieren sie ihre Fähigkeit, dürfen nicht nominieren und haben nur eine Stimme für den Rest des Spiels. Fähigkeiten, die im Tod wirken, sind Ausnahmen.','Les morts continuent de parler et partagent le résultat de leur équipe. Ils perdent normalement leur capacité et le droit de nommer ; il leur reste un seul vote pour la partie. Certaines capacités fonctionnent après la mort.','死者も会話し、陣営とともに勝敗が決まります。通常は能力と指名権を失い、残りのゲームで投票できるのは1回だけ。死後も働く能力は例外です。','Los muertos siguen hablando y comparten el resultado de su equipo. Normalmente pierden su habilidad y no pueden nominar; les queda un solo voto para toda la partida. Algunas habilidades funcionan estando muertos.'))
add('flow-states','flow',tr('취함·중독 / 별표','Drunk, poisoned / asterisk','Betrunken, vergiftet / Stern','Ivresse, poison / astérisque','酔い・毒 / アスタリスク','Ebriedad, veneno / asterisco'),tr('취하거나 중독되면 능력이 없지만 정상처럼 진행하며 거짓 정보를 받을 수 있습니다. 능력의 밤*은 첫날 밤을 제외한다는 뜻입니다. 대괄호 [ ]는 셋업 변경입니다.','Drunk or poisoned players have no ability, but play as though they do and may receive false information. Night* excludes the first night. Square brackets [ ] change setup.','Betrunkene oder Vergiftete haben keine Fähigkeit, werden aber behandelt, als hätten sie eine, und können falsche Informationen erhalten. Nacht* gilt nicht in der ersten Nacht. [ ] verändert den Aufbau.','Un joueur ivre ou empoisonné n’a plus de capacité, mais joue comme s’il en avait une et peut recevoir de fausses informations. Nuit* exclut la première nuit. [ ] modifie la mise en place.','酔い・毒の状態では能力がありませんが、能力があるかのように進行し、誤情報を受け取ることがあります。「夜*」は最初の夜を除きます。[ ] は準備時の変更です。','Un jugador ebrio o envenenado no tiene habilidad, pero actúa como si la tuviera y puede recibir información falsa. Noche* excluye la primera noche. [ ] modifica la preparación.'))
# Night orders are relative to the roles on each base script, not to characters actually in play.
phaseNames={'firstNight':tr('첫날 밤','First night','Erste Nacht','Première nuit','最初の夜','Primera noche'),'otherNight':tr('이후 밤','Other nights','Weitere Nächte','Nuits suivantes','以降の夜','Otras noches')}
info={'minioninfo':tr('하수인 정보','Minion information','Schergeninformation','Information des Sbires','手下の情報','Información de Esbirros'),'demoninfo':tr('악마 정보','Demon information','Dämoneninformation','Information du Démon','悪魔の情報','Información del Demonio')}
for e in ['tb','bmr','snv']:
 ids={r['id'] for r in roles if r['edition']==e and r['team']!='traveller'}
 for phase in ['firstNight','otherNight']:
  key=phase if phase in night else 'otherNights'
  order=[id for id in night[key] if id in ids or id in info]
  add(e+'-'+phase,'night',{l:edition(e,l)+' · '+phaseNames[phase][l] for l in langs},{l:' → '.join(info[id][l] if id in info else translations[l]['roles'][id]['name'] for id in order) for l in langs})
add('night-note','night',tr('순서 적용','Using the order','Reihenfolge anwenden','Utiliser cet ordre','順番の適用','Aplicar el orden'),tr('게임에 있는 역할만 깨우고 각 능력의 조건을 확인합니다. 여행자와 역할의 특수 처리도 적용하세요. 5·6인에서는 일반 하수인·악마 정보를 생략합니다.','Wake only characters in play when their ability applies. Apply Traveller abilities and special character instructions too. Omit normal Minion/Demon information with 5–6 players.','Wecke nur aktive Charaktere, deren Fähigkeit ansteht. Reisende und Sonderanweisungen ebenfalls beachten. Bei 5–6 Spielern entfällt die normale Schergen-/Dämoneninformation.','Réveillez seulement les personnages en jeu dont la capacité s’applique. Ajoutez les Voyageurs et les instructions particulières. À 5–6 joueurs, omettez les informations habituelles des Sbires et du Démon.','ゲーム中で能力条件を満たすキャラクターだけを起こします。旅人や特殊な処理も適用してください。5～6人では通常の手下・悪魔の情報を省略します。','Despierta solo a los personajes en juego cuya habilidad corresponda. Aplica también Viajeros e instrucciones especiales. Con 5–6 jugadores, omite la información habitual de Esbirros y Demonio.'))
for n,t,o,m in [(5,3,0,1),(6,3,1,1),(7,5,0,1),(8,5,1,1),(9,5,2,1),(10,7,0,2),(11,7,1,2),(12,7,2,2),(13,9,0,3),(14,9,1,3),(15,9,2,3)]:
 add('setup-'+str(n),'setup',tr(f'{n}인',f'{n} players',f'{n} Spieler',f'{n} joueurs',f'{n}人',f'{n} jugadores'),{l:' · '.join(f'{team(k,l)} {v}' for k,v in zip(teams,[t,o,m,1])) for l in langs})
add('setup-count','setup',tr('인원 계산·역할 조정','Counting & adjustments','Zählen & Anpassen','Décompte et ajustements','人数・役職の調整','Recuento y ajustes'),tr('표의 인원은 이야기꾼과 여행자를 제외합니다. 이야기꾼 1명이 별도로 필요합니다. 15명을 넘는 플레이어는 여행자로 참가합니다. 남작 등 [ ] 셋업 효과를 적용하고 토큰 수는 플레이어 수와 맞춥니다.','Counts exclude the Storyteller and Travellers. Add one Storyteller. Players beyond 15 join as Travellers. Apply bracketed setup effects such as the Baron; keep the token total equal to the non-Traveller player count.','Die Tabelle zählt ohne Erzähler und Reisende. Ein Erzähler kommt hinzu. Spieler über 15 sind Reisende. Aufbauänderungen in [ ], etwa des Barons, anwenden; die Tokenzahl bleibt gleich der Spielerzahl ohne Reisende.','Le tableau exclut le Conteur et les Voyageurs. Ajoutez un Conteur. Au-delà de 15, les joueurs sont des Voyageurs. Appliquez les effets [ ], comme celui du Baron ; le total de jetons reste égal au nombre de joueurs hors Voyageurs.','表は語り手と旅人を除いた人数です。別に語り手1人が必要。15人を超える参加者は旅人になります。男爵などの [ ] 効果を適用し、トークン総数は旅人以外の人数に合わせます。','La tabla excluye al Narrador y los Viajeros. Añade un Narrador. Más allá de 15, los jugadores son Viajeros. Aplica los efectos [ ], como el Barón; mantén tantos tokens como jugadores sin Viajeros.'))
add('setup-small','setup',tr('5·6인과 첫날 정보','5–6 players & opening information','5–6 Spieler & Startinformation','5–6 joueurs et informations initiales','5～6人と開始時情報','5–6 jugadores e información inicial'),tr('5·6인에서는 악마와 하수인이 서로를 모르고 악마는 블러프 역할 3개를 받지 않습니다. 7인 이상은 일반 첫날 악팀 정보를 제공합니다. 입문은 점철되는 혼란을 권장하며 다른 두 시나리오는 7인 이상을 권장합니다.','With 5–6 players, Demon and Minion do not learn each other and the Demon gets no three bluff characters. At 7+, give normal first-night evil-team information. Start with Trouble Brewing; the other two scripts are recommended for 7+.','Bei 5–6 erfahren Dämon und Scherge nicht voneinander; der Dämon erhält keine drei Bluffcharaktere. Ab 7 gilt die normale Startinformation. Für Einsteiger Trouble Brewing; die beiden anderen Skripte werden ab 7 empfohlen.','À 5–6, Démon et Sbire ne se connaissent pas et le Démon ne reçoit pas les trois bluffs. À 7+, donnez les informations initiales habituelles du Mal. Débutez avec Trouble Brewing ; les deux autres scénarios sont conseillés à 7+.','5～6人では悪魔と手下は互いを知らず、悪魔に3つのブラフ役職を教えません。7人以上は通常の最初の夜の悪陣営情報を伝えます。入門はトラブル・ブルイング、他2台本は7人以上を推奨。','Con 5–6, Demonio y Esbirro no se conocen y el Demonio no recibe tres faroles. Con 7+, da la información inicial habitual del mal. Empieza con Trouble Brewing; los otros dos guiones se recomiendan para 7+.'))
add('setup-prepare','setup',tr('공통 준비','Common preparation','Gemeinsame Vorbereitung','Préparation commune','共通の準備','Preparación común'),tr('시나리오 1개를 선택하고 역할표를 나눕니다. 원형으로 앉아 생명·투표 토큰을 준비합니다. 이야기꾼이 역할을 비밀리에 선택하고 셋업 효과를 적용한 뒤 토큰을 섞어 배분합니다. 마도서에 좌석 순서대로 기록하고 첫날 밤 순서표를 따릅니다.','Choose one script and distribute character sheets. Sit in a circle and prepare life/vote tokens. The Storyteller secretly selects characters, applies setup effects, shuffles and deals tokens, records seating in the Grimoire and follows the first-night order.','Ein Skript wählen, Charakterübersichten verteilen, im Kreis sitzen und Lebens-/Abstimmungsmarker bereitlegen. Der Erzähler wählt geheim Charaktere, wendet Aufbauänderungen an, mischt und verteilt Token, notiert die Sitzordnung im Grimoire und folgt der ersten Nacht.','Choisissez un scénario, distribuez les fiches et asseyez-vous en cercle avec jetons de vie et de vote. Le Conteur choisit secrètement les personnages, applique les effets de préparation, mélange et distribue les jetons, reporte les sièges dans le Grimoire puis suit la première nuit.','台本を1つ選び役職表を配り、円形に座って生存・投票トークンを準備します。語り手が役職を秘密に選び、準備効果を適用してトークンを混ぜて配布。魔導書に座席順を記録し、最初の夜の順番に従います。','Elige un guion y reparte hojas de personajes. Sentaos en círculo y prepara fichas de vida y voto. El Narrador elige personajes en secreto, aplica cambios, mezcla y reparte fichas, registra los asientos en el Grimorio y sigue el orden de la primera noche.'))
add('setup-carousel','setup',tr('캐러셀 사용','Using The Carousel','The Carousel verwenden','Utiliser The Carousel','The Carouselの使用','Usar The Carousel'),tr('캐러셀은 고정 시나리오가 아닌 추가 캐릭터 모음입니다. 선택한 스크립트의 역할표·밤 순서·공식 징크스를 사용하세요. [ ] 셋업 변경을 적용하며, 전설적·설화적 캐릭터는 일반 역할처럼 주머니에 넣어 배분하지 않습니다.','The Carousel is a character collection, not a fixed script. Use the selected script’s character sheet, night order and official jinxes. Apply [ ] setup changes; Fabled and Loric are not dealt from the bag as ordinary roles.','The Carousel ist eine Charaktersammlung, kein festes Skript. Nutzt Charakterübersicht, Nachtreihenfolge und offizielle Jinx-Regeln des gewählten Skripts. [ ] verändert den Aufbau; Legenden und Loric werden nicht als normale Rollen aus dem Beutel verteilt.','The Carousel est une collection de personnages, pas un scénario fixe. Utilisez la fiche, l’ordre nocturne et les jinx officiels du scénario choisi. Appliquez les changements [ ] ; les Légendaires et Loric ne sont pas distribués dans le sac comme des rôles ordinaires.','The Carouselは固定台本ではなく追加キャラクター集です。選んだ台本の役職表・夜順・公式ジンクスを使用し、[ ]の準備変更を適用します。伝説とロリクは通常の役職として袋から配りません。','The Carousel es una colección de personajes, no un guion fijo. Usa la hoja, el orden nocturno y los jinx oficiales del guion elegido. Aplica cambios [ ]; Fábulas y Lóric no se reparten desde la bolsa como roles normales.'))
data['source']['carousel']='https://bloodontheclocktower.com/collections/carousel-character-tokens'
data['source']['koreanPublisher']='https://m.mtsgames.kr/news/read.html?board_no=2&no=6187'
data['source']['customScripts']=[{'name':script['name'],'author':script['author'],'version':script['version'],'url':script['source']} for script in custom_scripts]
data['source']['namingNote']='Character and script names follow TPI app translations; these are not independently verified physical-edition translations. Unverified localized product titles retain The Carousel.'

# Keep the Korean physical-edition terminology consistent in generated copy.
def replace_korean_term(value):
 if isinstance(value, dict):
  return {
   key: (item.replace('외지인', '이방인') if key == 'ko' and isinstance(item, str)
         else replace_korean_term(item))
   for key, item in value.items()
  }
 if isinstance(value, list): return [replace_korean_term(item) for item in value]
 return value
data = replace_korean_term(data)
(target/'reference.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
p=Path('data/games.json');catalog=json.loads(p.read_text(encoding='utf-8'));catalog=[g for g in catalog if g['id']!='clocktower'];catalog.insert(3,{'id':'clocktower','title':titles['en'],'titles':titles,'href':'./clocktower/','reference':'clocktower/reference.json','languages':langs,'tag':tr('사회적 추리','Social deduction','Soziale Deduktion','Déduction sociale','正体隠匿','Deducción social'),'description':description,'actionKey':'enterAction','statusLabel':'OPEN','bg':'linear-gradient(135deg, #170d25, #6b1837, #150e21)','cover':'clocktower/images/cover.svg'});p.write_text(json.dumps(catalog,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Imported {len(roles)} roles; {len(data["items"])} total entries in {len(langs)} languages.')
